

export const QuranLinks = [
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0001.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0002.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0003.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0004.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0005.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0006.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0007.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0008.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0009.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0010.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0011.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0012.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0013.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0014.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0015.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0016.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0017.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0018.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0019.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0020.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0021.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0022.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0023.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0024.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0025.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0026.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0027.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0028.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0029.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0030.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0031.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0032.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0033.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0034.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0035.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0036.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0037.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0038.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0039.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0040.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0041.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0042.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0043.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0044.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0045.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0046.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0047.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0048.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0049.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0050.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0051.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0052.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0053.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0054.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0055.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0056.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0057.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0058.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0059.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0060.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0061.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0062.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0063.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0064.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0065.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0066.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0067.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0068.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0069.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0070.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0071.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0072.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0073.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0074.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0075.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0076.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0077.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0078.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0079.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0080.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0081.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0082.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0083.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0084.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0085.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0086.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0087.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0088.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0089.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0090.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0091.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0092.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0093.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0094.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0095.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0096.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0097.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0098.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0099.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0100.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0101.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0102.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0103.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0104.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0105.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0106.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0107.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0108.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0109.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0110.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0111.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0112.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0113.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0114.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0115.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0116.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0117.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0118.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0119.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0120.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0121.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0122.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0123.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0124.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0125.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0126.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0127.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0128.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0129.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0130.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0131.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0132.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0133.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0134.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0135.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0136.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0137.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0138.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0139.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0140.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0141.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0142.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0143.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0144.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0145.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0146.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0147.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0148.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0149.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0150.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0151.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0152.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0153.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0154.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0155.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0156.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0157.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0158.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0159.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0160.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0161.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0162.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0163.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0164.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0165.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0166.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0167.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0168.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0169.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0170.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0171.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0172.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0173.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0174.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0175.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0176.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0177.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0178.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0179.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0180.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0181.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0182.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0183.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0184.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0185.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0186.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0187.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0188.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0189.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0190.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0191.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0192.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0193.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0194.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0195.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0196.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0197.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0198.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0199.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0200.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0201.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0202.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0203.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0204.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0205.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0206.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0207.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0208.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0209.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0210.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0211.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0212.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0213.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0214.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0215.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0216.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0217.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0218.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0219.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0220.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0221.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0222.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0223.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0224.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0225.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0226.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0227.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0228.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0229.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0230.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0231.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0232.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0233.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0234.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0235.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0236.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0237.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0238.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0239.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0240.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0241.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0242.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0243.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0244.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0245.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0246.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0247.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0248.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0249.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0250.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0251.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0252.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0253.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0254.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0255.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0256.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0257.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0258.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0259.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0260.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0261.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0262.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0263.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0264.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0265.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0266.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0267.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0268.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0269.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0270.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0271.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0272.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0273.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0274.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0275.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0276.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0277.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0278.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0279.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0280.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0281.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0282.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0283.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0284.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0285.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0286.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0287.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0288.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0289.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0290.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0291.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0292.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0293.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0294.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0295.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0296.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0297.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0298.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0299.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0300.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0301.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0302.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0303.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0304.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0305.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0306.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0307.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0308.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0309.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0310.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0311.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0312.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0313.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0314.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0315.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0316.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0317.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0318.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0319.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0320.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0321.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0322.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0323.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0324.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0325.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0326.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0327.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0328.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0329.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0330.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0331.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0332.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0333.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0334.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0335.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0336.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0337.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0338.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0339.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0340.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0341.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0342.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0343.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0344.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0345.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0346.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0347.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0348.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0349.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0350.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0351.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0352.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0353.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0354.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0355.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0356.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0357.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0358.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0359.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0360.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0361.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0362.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0363.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0364.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0365.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0366.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0367.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0368.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0369.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0370.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0371.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0372.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0373.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0374.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0375.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0376.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0377.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0378.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0379.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0380.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0381.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0382.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0383.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0384.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0385.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0386.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0387.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0388.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0389.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0390.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0391.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0392.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0393.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0394.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0395.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0396.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0397.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0398.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0399.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0400.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0401.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0402.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0403.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0404.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0405.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0406.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0407.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0408.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0409.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0410.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0411.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0412.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0413.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0414.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0415.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0416.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0417.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0418.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0419.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0420.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0421.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0422.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0423.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0424.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0425.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0426.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0427.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0428.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0429.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0430.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0431.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0432.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0433.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0434.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0435.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0436.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0437.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0438.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0439.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0440.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0441.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0442.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0443.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0444.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0445.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0446.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0447.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0448.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0449.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0450.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0451.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0452.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0453.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0454.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0455.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0456.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0457.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0458.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0459.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0460.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0461.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0462.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0463.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0464.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0465.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0466.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0467.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0468.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0469.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0470.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0471.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0472.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0473.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0474.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0475.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0476.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0477.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0478.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0479.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0480.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0481.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0482.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0483.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0484.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0485.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0486.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0487.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0488.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0489.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0490.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0491.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0492.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0493.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0494.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0495.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0496.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0497.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0498.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0499.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0500.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0501.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0502.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0503.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0504.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0505.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0506.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0507.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0508.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0509.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0510.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0511.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0512.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0513.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0514.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0515.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0516.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0517.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0518.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0519.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0520.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0521.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0522.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0523.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0524.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0525.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0526.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0527.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0528.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0529.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0530.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0531.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0532.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0533.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0534.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0535.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0536.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0537.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0538.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0539.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0540.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0541.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0542.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0543.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0544.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0545.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0546.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0547.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0548.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0549.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0550.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0551.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0552.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0553.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0554.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0555.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0556.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0557.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0558.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0559.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0560.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0561.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0562.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0563.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0564.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0565.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0566.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0567.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0568.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0569.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0570.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0571.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0572.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0573.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0574.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0575.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0576.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0577.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0578.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0579.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0580.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0581.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0582.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0583.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0584.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0585.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0586.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0587.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0588.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0589.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0590.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0591.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0592.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0593.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0594.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0595.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0596.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0597.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0598.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0599.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0600.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0601.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0602.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0603.jpg",
  "https://raw.githubusercontent.com/HoSheiMa/quran-native-application/master/assets/quran/0604.jpg",
]


export const QuranTrans = [
    {
        "Title" : 'English Quran',
        "IdNmae" : 'Quran_EN',
        size: 4,
        "ControllName": 'Quran_EN_Control',
        "IdExistName": "Quran_EN_Exist",
        "JsonImagesLinks" : 'https://qandil-afa.000webhostapp.com/react_native_quran_app/Quran_EN_Images.json',
        "JsonImageControlDATA" : 'https://qandil-afa.000webhostapp.com/react_native_quran_app/Quran_EN_ImageControl.json',
    },
    {
        "Title" : 'English Quran',
        "IdNmae" : 'Quran_EN',
        size: 4,
        "ControllName": 'Quran_EN_Control',
        "IdExistName": "Quran_EN_Exist2",
        "JsonImagesLinks" : 'https://qandil-afa.000webhostapp.com/react_native_quran_app/Quran_EN_Images.json',
        "JsonImageControlDATA" : 'https://qandil-afa.000webhostapp.com/react_native_quran_app/Quran_EN_ImageControl.json',
    },
    {
        "Title" : 'English Quran',
        "IdNmae" : 'Quran_EN',
        size: 4,
        "ControllName": 'Quran_EN_Control',
        "IdExistName": "Quran_EN_Exist3",
        "JsonImagesLinks" : 'https://qandil-afa.000webhostapp.com/react_native_quran_app/Quran_EN_Images.json',
        "JsonImageControlDATA" : 'https://qandil-afa.000webhostapp.com/react_native_quran_app/Quran_EN_ImageControl.json',
    },

]
export const  pagenumData = [
    [0, 7, 5, 1, 'الفاتحة', "Al-Fatiha", 'The Opening', 'Meccan'],
    [7, 286, 87, 40, 'البقرة', "Al-Baqara", 'The Heifer', 'Medinan'],
    [
      293,
      200,
      89,
      20,
      'آل عمران',
      "Al-i-Imran",
      'The Family of Imran',
      'Medinan'
    ],
    [493, 176, 92, 24, 'النساء', "An-Nisa", 'The Women', 'Medinan'],
    [669, 120, 112, 16, 'المائدة', "Al-Ma'ida", 'The Table', 'Medinan'],
    [789, 165, 55, 20, 'الأنعام', "Al-An'am", 'The Cattle', 'Meccan'],
    [954, 206, 39, 24, 'الأعراف', "Al-A'raf", 'The Heights', 'Meccan'],
    [1160, 75, 88, 10, 'الأنفال', "Al-Anfal", 'The Spoils of War', 'Medinan'],
    [1235, 129, 113, 16, 'التوبة', "At-Tawba", 'The Repentance', 'Medinan'],
    [1364, 109, 51, 11, 'يونس', "Yunus", 'Jonah', 'Meccan'],
    [1473, 123, 52, 10, 'هود', "Hud", 'Hud', 'Meccan'],
    [1596, 111, 53, 12, 'يوسف', "Yusuf", 'Joseph', 'Meccan'],
    [1707, 43, 96, 6, 'الرعد', "Ar-Ra'd", 'The Thunder', 'Medinan'],
    [1750, 52, 72, 7, 'ابراهيم', "Ibrahim", 'Abraham', 'Meccan'],
    [1802, 99, 54, 6, 'الحجر', "Al-Hijr", 'The Stoneland', 'Meccan'],
    [1901, 128, 70, 16, 'النحل', "An-Nahl", 'The Honey Bees', 'Meccan'],
    [2029, 111, 50, 12, 'الإسراء', "Al-Isra", 'The Night Journey', 'Meccan'],
    [2140, 110, 69, 12, 'الكهف', "Al-Kahf", 'The Cave', 'Meccan'],
    [2250, 98, 44, 6, 'مريم', "Maryam", 'Mary', 'Meccan'],
    [2348, 135, 45, 8, 'طه', "Ta-Ha", 'Ta-Ha', 'Meccan'],
    [2483, 112, 73, 7, 'الأنبياء', "Al-Anbiya", 'The Prophets', 'Meccan'],
    [2595, 78, 103, 10, 'الحج', "Al-Hajj", 'The Pilgrimage', 'Medinan'],
    [2673, 118, 74, 6, 'المؤمنون', "Al-Mu'minun", 'The Believers', 'Meccan'],
    [2791, 64, 102, 9, 'النور', "An-Nur", 'The Light', 'Medinan'],
    [2855, 77, 42, 6, 'الفرقان', "Al-Furqan", 'The Criterion', 'Meccan'],
    [2932, 227, 47, 11, 'الشعراء', "Ash-Shu'ara", 'The Poets', 'Meccan'],
    [3159, 93, 48, 7, 'النمل', "An-Naml", 'The Ant', 'Meccan'],
    [3252, 88, 49, 9, 'القصص', "Al-Qasas", 'The Stories', 'Meccan'],
    [3340, 69, 85, 7, 'العنكبوت', "Al-Ankabut", 'The Spider', 'Meccan'],
    [3409, 60, 84, 6, 'الروم', "Ar-Rum", 'The Romans', 'Meccan'],
    [3469, 34, 57, 4, 'لقمان', "Luqman", 'Luqman', 'Meccan'],
    [3503, 30, 75, 3, 'السجدة', "As-Sajda", 'The Prostration', 'Meccan'],
    [3533, 73, 90, 9, 'الأحزاب', "Al-Ahzab", 'The Clans', 'Medinan'],
    [3606, 54, 58, 6, 'سبإ', "Saba", 'Sheba', 'Meccan'],
    [3660, 45, 43, 5, 'فاطر', "Fatir", 'The Originator', 'Meccan'],
    [3705, 83, 41, 5, 'يس', "Ya-Sin", 'Yaseen', 'Meccan'],
    [3788, 182, 56, 5, 'الصافات', "As-Saffat", 'Drawn up in Ranks', 'Meccan'],
    [3970, 88, 38, 5, 'ص', "Sad", 'The Letter Sad', 'Meccan'],
    [4058, 75, 59, 8, 'الزمر', "Az-Zumar", 'The Troops', 'Meccan'],
    [4133, 85, 60, 9, 'غافر', "Ghafir", 'The Forgiver', 'Meccan'],
    [4218, 54, 61, 6, 'فصلت', "Fussilat", 'Explained in Detail', 'Meccan'],
    [4272, 53, 62, 5, 'الشورى', "Ash-Shura", 'The Consultation', 'Meccan'],
    [
      4325,
      89,
      63,
      7,
      'الزخرف',
      "Az-Zukhruf",
      'The Ornaments of Gold',
      'Meccan'
    ],
    [4414, 59, 64, 3, 'الدخان', "Ad-Dukhan", 'The Smoke', 'Meccan'],
    [4473, 37, 65, 4, 'الجاثية', "Al-Jathiya", 'Crouching', 'Meccan'],
    [4510, 35, 66, 4, 'الأحقاف', "Al-Ahqaf", 'The Dunes', 'Meccan'],
    [4545, 38, 95, 4, 'محمد', "Muhammad", 'Muhammad', 'Medinan'],
    [4583, 29, 111, 4, 'الفتح', "Al-Fath", 'The Victory', 'Medinan'],
    [
      4612,
      18,
      106,
      2,
      'الحجرات',
      "Al-Hujurat",
      'The Inner Apartments',
      'Medinan'
    ],
    [4630, 45, 34, 3, 'ق', "Qaf", 'The Letter Qaf', 'Meccan'],
    [
      4675,
      60,
      67,
      3,
      'الذاريات',
      "Adh-Dhariyat",
      'The Winnowing Winds',
      'Meccan'
    ],
    [4735, 49, 76, 2, 'الطور', "At-Tur", 'The Mount', 'Meccan'],
    [4784, 62, 23, 3, 'النجم', "An-Najm", 'The Star', 'Meccan'],
    [4846, 55, 37, 3, 'القمر', "Al-Qamar", 'The Moon', 'Meccan'],
    [4901, 78, 97, 3, 'الرحمن', "Ar-Rahman", 'The Beneficent', 'Medinan'],
    [4979, 96, 46, 3, 'الواقعة', "Al-Waqi'a", 'The Inevitable', 'Meccan'],
    [5075, 29, 94, 4, 'الحديد', "Al-Hadid", 'The Iron', 'Medinan'],
    [5104, 22, 105, 3, 'المجادلة', "Al-Mujadila", 'The Pleading', 'Medinan'],
    [5126, 24, 101, 3, 'الحشر', "Al-Hashr", 'The Exile', 'Medinan'],
    [5150, 13, 91, 2, 'الممتحنة', "Al-Mumtahina", 'Examining Her', 'Medinan'],
    [5163, 14, 109, 2, 'الصف', "As-Saff", 'The Ranks', 'Medinan'],
    [5177, 11, 110, 2, 'الجمعة', "Al-Jumu'a", 'Friday', 'Medinan'],
    [
      5188,
      11,
      104,
      2,
      'المنافقون',
      "Al-Munafiqun",
      'The Hypocrites',
      'Medinan'
    ],
    [
      5199,
      18,
      108,
      2,
      'التغابن',
      "At-Taghabun",
      'Mutual Disillusion',
      'Medinan'
    ],
    [5217, 12, 99, 2, 'الطلاق', "At-Talaq", 'Divorce', 'Medinan'],
    [5229, 12, 107, 2, 'التحريم', "At-Tahrim", 'The Prohibition', 'Medinan'],
    [5241, 30, 77, 2, 'الملك', "Al-Mulk", 'The Sovereignty', 'Meccan'],
    [5271, 52, 2, 2, 'القلم', "Al-Qalam", 'The Pen', 'Meccan'],
    [5323, 52, 78, 2, 'الحاقة', "Al-Haqqa", 'The Reality', 'Meccan'],
    [
      5375,
      44,
      79,
      2,
      'المعارج',
      "Al-Ma'arij",
      'The Ascending Stairways',
      'Meccan'
    ],
    [5419, 28, 71, 2, 'نوح', "Nuh", 'Noah', 'Meccan'],
    [5447, 28, 40, 2, 'الجن', "Al-Jinn", 'The Jinn', 'Meccan'],
    [5475, 20, 3, 2, 'المزمل', "Al-Muzzammil", 'The Enshrouded One', 'Meccan'],
    [5495, 56, 4, 2, 'المدثر', "Al-Muddathir", 'The Cloaked One', 'Meccan'],
    [5551, 40, 31, 2, 'القيامة', "Al-Qiyama", 'The Resurrection', 'Meccan'],
    [5591, 31, 98, 2, 'الانسان', "Al-Insan", 'Human', 'Medinan'],
    [5622, 50, 33, 2, 'المرسلات', "Al-Mursalat", 'The Emissaries', 'Meccan'],
    [5672, 40, 80, 2, 'النبإ', "An-Naba'", 'The Announcement', 'Meccan'],
    [
      5712,
      46,
      81,
      2,
      'النازعات',
      "An-Nazi'at",
      'Those Who Drag Forth',
      'Meccan'
    ],
    [5758, 42, 24, 1, 'عبس', "Abasa", 'He Frowned', 'Meccan'],
    [5800, 29, 7, 1, 'التكوير', "At-Takwir", 'The Folding Up', 'Meccan'],
    [5829, 19, 82, 1, 'الإنفطار', "Al-Infitar", 'The Cleaving', 'Meccan'],
    [5848, 36, 86, 1, 'المطففين', "Al-Mutaffifin", 'Defrauding', 'Meccan'],
    [
      5884,
      25,
      83,
      1,
      'الإنشقاق',
      "Al-Inshiqaq",
      'The Splitting Open',
      'Meccan'
    ],
    [5909, 22, 27, 1, 'البروج', "Al-Buruj", 'The Constellations', 'Meccan'],
    [5931, 17, 36, 1, 'الطارق', "At-Tariq", 'The Morning Star', 'Meccan'],
    [5948, 19, 8, 1, 'الأعلى', "Al-A'la", 'The Most High', 'Meccan'],
    [5967, 26, 68, 1, 'الغاشية', "Al-Ghashiya", 'The Overwhelming', 'Meccan'],
    [5993, 30, 10, 1, 'الفجر', "Al-Fajr", 'The Dawn', 'Meccan'],
    [6023, 20, 35, 1, 'البلد', "Al-Balad", 'The City', 'Meccan'],
    [6043, 15, 26, 1, 'الشمس', "Ash-Shams", 'The Sun', 'Meccan'],
    [6058, 21, 9, 1, 'الليل', "Al-Lail", 'The Night', 'Meccan'],
    [6079, 11, 11, 1, 'الضحى', "Ad-Dhuha", 'The Morning Hours', 'Meccan'],
    [6090, 8, 12, 1, 'الشرح', "Ash-Sharh", 'The Consolation', 'Meccan'],
    [6098, 8, 28, 1, 'التين', "At-Tin", 'The Fig', 'Meccan'],
    [6106, 19, 1, 1, 'العلق', "Al-Alaq", 'The Clot', 'Meccan'],
    [6125, 5, 25, 1, 'القدر', "Al-Qadr", 'The Power, Fate', 'Meccan'],
    [6130, 8, 100, 1, 'البينة', "Al-Bayyina", 'The Evidence', 'Medinan'],
    [6138, 8, 93, 1, 'الزلزلة', "Az-Zalzala", 'The Earthquake', 'Medinan'],
    [6146, 11, 14, 1, 'العاديات', "Al-Adiyat", 'The Chargers', 'Meccan'],
    [6157, 11, 30, 1, 'القارعة', "Al-Qari'a", 'The Calamity', 'Meccan'],
    [6168, 8, 16, 1, 'التكاثر', "At-Takathur", 'Competition', 'Meccan'],
    [6176, 3, 13, 1, 'العصر', "Al-Asr", 'The Time', 'Meccan'],
    [6179, 9, 32, 1, 'الهمزة', "Al-Humaza", 'The Traducer', 'Meccan'],
    [6188, 5, 19, 1, 'الفيل', "Al-Fil", 'The Elephant', 'Meccan'],
    [6193, 4, 29, 1, 'قريش', "Quraysh", 'Quraysh', 'Meccan'],
    [6197, 7, 17, 1, 'الماعون', "Al-Ma'un", 'Almsgiving', 'Meccan'],
    [6204, 3, 15, 1, 'الكوثر', "Al-Kawthar", 'Abundance', 'Meccan'],
    [6207, 6, 18, 1, 'الكافرون', "Al-Kafirun", 'The Disbelievers', 'Meccan'],
    [6213, 3, 114, 1, 'النصر', "An-Nasr", 'Divine Support', 'Medinan'],
    [6216, 5, 6, 1, 'المسد', "Al-Masad", 'The Palm Fibre', 'Meccan'],
    [6221, 4, 22, 1, 'الإخلاص', "Al-Ikhlas", 'Purity of Faith', 'Meccan'],
    [6225, 5, 20, 1, 'الفلق', "Al-Falaq", 'The Dawn', 'Meccan'],
    [6230, 6, 21, 1, 'الناس', "An-Nas", 'Mankind', 'Meccan'],
    [6236, 1]
  ];
export const pagenum = [
    1,
    2,
    50,
    77,
    106,
    128,
    151,
    177,
    187,
    208,
    221,
    235,
    249,
    255,
    262,
    267,
    282,
    293,
    305,
    312,
    322,
    332,
    342,
    350,
    359,
    367,
    377,
    385,
    396,
    404,
    411,
    415,
    418,
    428,
    434,
    440,
    446,
    453,
    458,
    467,
    477,
    483,
    489,
    496,
    499,
    502,
    507,
    511,
    515,
    518,
    520,
    523,
    526,
    528,
    531,
    534,
    537,
    542,
    545,
    549,
    551,
    553,
    554,
    556,
    558,
    560,
    562,
    564,
    566,
    568,
    570,
    572,
    574,
    575,
    577,
    578,
    580,
    582,
    583,
    585,
    586,
    587,
    587,
    589,
    590,
    591,
    591,
    592,
    593,
    594,
    595,
    595,
    596,
    596,
    597,
    597,
    598,
    598,
    599,
    599,
    600,
    600,
    601,
    601,
    601,
    602,
    602,
    602,
    603,
    603,
    603,
    604,
    604,
    604,
  ];